DOCKER

diff --git a/OneDrive/Desktop/Devops/.github/workflow/ci.yml b/OneDrive/Desktop/Devops/.github/workflow/ci.yml
--- a/OneDrive/Desktop/Devops/.github/workflow/ci.yml
+++ b/OneDrive/Desktop/Devops/.github/workflow/ci.yml
@@ -1,81 +1,81 @@
-name: CI-CD Pipeline
 
-on:
-  push:
-    branches:
-      - main
+# name: CI-CD Pipeline
 
-permissions:
-  contents: read
-  pages: write
-  id-token: write
+# on:
+#   push:
+#     branches:
+#       - main
 
-jobs:
+# permissions:
+#   contents: read
+#   pages: write
+#   id-token: write
 
-  build:
-    runs-on: ubuntu-latest
+# jobs:
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v6
+#   build:
+#     runs-on: ubuntu-latest
 
-      - name: Build website
-        run: |
-          mkdir build
-          cp index.html build/
-          cp style.css build/
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v6
 
-      - name: Upload build
-        uses: actions/upload-artifact@v4
-        with:
-          name: website-build
-          path: build/
+#       - name: Build website
+#         run: |
+#           mkdir build
+#           cp index.html build/
+#           cp style.css build/
 
-  test:
-    runs-on: ubuntu-latest
-    needs: build
+#       - name: Upload build
+#         uses: actions/upload-artifact@v4
+#         with:
+#           name: website-build
+#           path: build/
 
-    steps:
-      - name: Download build
-        uses: actions/download-artifact@v4
-        with:
-          name: website-build
-          path: build/
+#   test:
+#     runs-on: ubuntu-latest
+#     needs: build
 
-      - name: Test website
-        run: |
-          if [ -f "build/index.html" ] && [ -f "build/style.css" ]; then
-            echo "Website files found successfully."
-          else
-            echo "Website files are missing."
-            exit 1
-          fi
+#     steps:
+#       - name: Download build
+#         uses: actions/download-artifact@v4
+#         with:
+#           name: website-build
+#           path: build/
 
-      - name: Upload Pages artifact
-        uses: actions/upload-pages-artifact@v4
-        with:
-          path: './build'
+  #     - name: Test website
+  #       run: |
+  #         if [ -f "build/index.html" ] && [ -f "build/style.css" ]; then
+  #           echo "Website files found successfully."
+  #         else
+  #           echo "Website files are missing."
+  #           exit 1
+  #         fi
 
-  deploy:
-    runs-on: ubuntu-latest
-    needs: test
+  #     - name: Upload Pages artifact
+  #       uses: actions/upload-pages-artifact@v4
+  #       with:
+  #         path: './build'
 
-    environment:
-      name: github-pages
-      url: ${{ steps.deployment.outputs.page_url }}
+  # deploy:
+  #   runs-on: ubuntu-latest
+  #   needs: test
 
-    steps:
-      - name: Deploy to GitHub Pages
-        id: deployment
-        uses: actions/deploy-pages@v4
+  #   environment:
+  #     name: github-pages
+  #     url: ${{ steps.deployment.outputs.page_url }}
 
-
+  #   steps:
+  #     - name: Deploy to GitHub Pages
+  #       id: deployment
+  #       uses: actions/deploy-pages@v4
+    
 
         name: Build and Push Docker Image
 
         on:
         push:
-        branches: ["main"]
+        branches: ["master"]
 
 jobs:
   build-and-push:
@@ -88,8 +88,8 @@ jobs:
       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
-          username: ${{ secrets.mitali1508 }}
-          password: ${{ secrets.mitali152003 }}
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
 
       - name: Build and Push Docker Image
         uses: docker/build-push-action@v5
